sudo: required
language: generic
services:
    - docker

before_install:
    - docker build -t ranjithraj3/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true ranjithraj3/docker-react npm run test -- --coverage